import type { Metadata } from 'next';
import { Space_Grotesk } from 'next/font/google';
import './globals.css';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Nav from '@/components/root/Nav';
import Script from 'next/script';
import Head from 'next/head';
import ConfigProvider from '@/components/root/ConfigProvider';
import { Root } from '@/components/root/Root';

const space_grotest = Space_Grotesk({ subsets: ['latin'] });
export const metadata: Metadata = {
  title: 'TON Game',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
      </Head>
      <body className={space_grotest.className + ' min-h-screen bg-[#0A051E]'}>
        <AntdRegistry>
          <ConfigProvider>
            <Root>
              {children}
              <Nav />
            </Root>
          </ConfigProvider>
        </AntdRegistry>
        <Script src="/js/telegram-web-app.js" strategy="lazyOnload" />
      </body>
    </html>
  );
}
